### PR TITLE
pytest html for ui (all actually)

### PR DESCRIPTION
**Pull request by mganisin**
- Instakk also pytest-html
- junitxml name based just on basename
- Add UI screenshot reference to pytest-html report
- Automatically generate html report for UI

### CODE REVIEW

**Comment by dhlavac** [comment]
What about default gitignore result dir in test suite, when there is none specified

**Review by mdujava — DISMISSED** [review]

**Review by jsmolar — DISMISSED** [review]

**Review by dhlavac — APPROVED** [review]

**Review by dhlavac — CHANGES_REQUESTED** [review]
When running tests from a specific directory(not the testsuite root) no screenshots are added to the HTML report. Could it be possible, to save the report by default to the same directory as screenshots are saved?

**Comment by mganisin** [comment]
> When running tests from a specific directory(not the testsuite root) no screenshots are added to the HTML report. Could it be possible, to save the report by default to the same directory as screenshots are saved?

@dhlavac path to report is set on commandline, unlikely good idea to alter it as it wouldn't have to be clear when to modify it and when not. It's better idea to set it on command line with absolute path.

The issue with links to the screenshots should be fixed, they should be present correctly in html report now. Try it, please

**Review by mdujava — APPROVED** [review]

**Review by dhlavac — APPROVED** [review]

**Comment by dhlavac** [comment]
LGTM!!!

**Pull request merged**
